/*
 * Report.cpp - TaskJuggler
 *
 * Copyright (c) 2001, 2002, 2003 by Chris Schlaeger <cs@suse.de>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * $Id$
 */

#include <config.h>

#include "HTMLReport.h"
#include "Project.h"

HTMLReport::HTMLReport(Project* p, const QString& f, const QString& df, 
                       int dl) :
   Report(p, f, df, dl)
{
}

void
HTMLReport::generateHeader()
{
    s << "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">"
      << endl
      << "<!-- Generated by TaskJuggler v"VERSION" -->" << endl
      << "<!-- For details about TaskJuggler see "
      << TJURL << " -->" << endl
      << "<html>" << endl
      << "<head>" << endl
      << "<title>Task Report</title>" << endl
      << "<meta http-equiv=\"Content-Type\" content=\"text/html; "
      << "charset=utf-8\">" << endl
      << "</head>" << endl
      << "<body>" << endl;

    if (!rawHead.isEmpty())
        s << rawHead << endl;
    if (!headline.isEmpty())
        s << "<h1>" << htmlFilter(headline) << "</h1>" << endl;
    if (!caption.isEmpty())
        s << "<p>" << htmlFilter(caption) << "</p>" << endl;
}

void
HTMLReport::generateFooter()
{
    if (!rawTail.isEmpty())
        s << rawTail << endl;

    s << "<p><span style=\"font-size:0.7em\">";
    if (!project->getCopyright().isEmpty())
        s << htmlFilter(project->getCopyright()) << " - ";
    s << "Version " << htmlFilter(project->getVersion())
      << " - Created with <a HREF=\"" << TJURL <<
      "\">TaskJuggler</a> <a HREF=\"" << TJURL << "/download.php\">v"
      << VERSION << "</a></span></p>" << endl << "</body>\n";
}

