/*
 * Report.cpp - TaskJuggler
 *
 * Copyright (c) 2001, 2002, 2003 by Chris Schlaeger <cs@suse.de>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * $Id$
 */

#include <config.h>

#include "HTMLReport.h"
#include "Project.h"

HTMLReport::HTMLReport(Project* p, const QString& f, const QString& df, 
                       int dl) :
   Report(p, f, df, dl)
{
    colDefault = 0xf3ebae;
    colDefaultLight = 0xfffadd;
    colWeekend = 0xffec80;
    colVacation = 0xfffc60;
    colAvailable = 0xa4ff8d;
    colBooked = 0xff5a5d;
    colBookedLight = 0xffbfbf;
    colHeader = 0xa5c2ff;
    colMilestone = 0xff2a2a;
    colCompleted = 0x87ff75;
    colCompletedLight = 0xa1ff9a;
    colToday = 0xa387ff;
}

void
HTMLReport::generateHeader()
{
    s << "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">"
      << endl
      << "<!-- Generated by TaskJuggler v"VERSION" -->" << endl
      << "<!-- For details about TaskJuggler see "
      << TJURL << " -->" << endl
      << "<html>" << endl
      << "<head>" << endl
      << "<title>Task Report</title>" << endl
      << "<meta http-equiv=\"Content-Type\" content=\"text/html; "
      << "charset=utf-8\">" << endl
      << "<style type=\"text/css\"><!--" << endl;
    if (rawStyleSheet.isEmpty())
    {
        s.reset();
        s.setf(QTextStream::hex);
        s << ".default { background-color:#" << colDefault
            << "; font-size:70%; text-align:center }" << endl
            << ".defaultlight { background-color:#" << colDefaultLight
            << "; font-size:70%; text-align:center }" << endl
            << ".task { background-color:#" << colDefault
            << "; font-size:100%; text-align:left }" << endl
            << ".tasklight { background-color:#" << colDefaultLight
            << "; font-size:100%; text-align:left }" << endl
            << ".available { background-color:#" << colAvailable
            << "; font-size:70%; text-align:center }" << endl
            << ".vacation { background-color:#" << colVacation
            << "; font-size:70%; text-align:center }" << endl
            << ".weekend { background-color:#" << colWeekend
            << "; font-size:70%; text-align:center }" << endl
            << ".milestone { background-color:#" << colMilestone
            << "; font-size:70%; text-align:center }" << endl
            << ".booked { background-color:#" << colBooked
            << "; font-size:70%; text-align:center }" << endl
            << ".bookedlight { background-color:#" << colBookedLight
            << "; font-size:70%; text-align:center }" << endl
            << ".headersmall { background-color:#" << colHeader
            << "; font-size:70%; text-align:center }" << endl
            << ".headerbig { background-color:#" << colHeader
            << "; font-size:110%; font-weight:bold; text-align:center }" << endl
            << ".completed { background-color:#" << colCompleted
            << "; font-size:70%; text-align:center }" << endl
            << ".completedlight { background-color:#" << colCompletedLight
            << "; font-size:70%; text-align:center }" << endl
            << ".today { background-color:#" << colToday
            << "; font-size:70%; text-align:center }" << endl;
    }
    else
        s << rawStyleSheet << endl;
    s << "--></style>" << endl;
    s << "</head>" << endl
      << "<body>" << endl;

    if (!rawHead.isEmpty())
        s << rawHead << endl;
    if (!headline.isEmpty())
        s << "<h1>" << htmlFilter(headline) << "</h1>" << endl;
    if (!caption.isEmpty())
        s << "<p>" << htmlFilter(caption) << "</p>" << endl;
}

void
HTMLReport::generateFooter()
{
    if (!rawTail.isEmpty())
        s << rawTail << endl;

    s << "<p><span style=\"font-size:0.7em\">";
    if (!project->getCopyright().isEmpty())
        s << htmlFilter(project->getCopyright()) << " - ";
    s << "Version " << htmlFilter(project->getVersion())
      << " - Created with <a HREF=\"" << TJURL <<
      "\">TaskJuggler v"
      << VERSION << "</a></span></p>" << endl << "</body>\n";
}

