#! /bin/sh

grep '.*KW(".*").*' ../../taskjuggler/*.cpp ../../taskjuggler/*.h |\
tr ' ' '\n' | grep '.*KW(".*").*' |\
sed 's%.*KW("\(.*\)").*%syn keyword tjpkeyword \1%g' | sort -u > \
center

cat head.vim center tail.vim > tjp.vim

