#!/bin/bash
#
# Create a taskjuggler tarball in the current directory
#
# Copyright 2003 Klaas Freitag <freitag@suse.de>
# 
# Parameter 1: The required version (defaults to svn)
# Parameter 2: The branch or release (defaults to HEAD)
#
tmpdir=/tmp/taskjuggler-$RANDOM
v=svn
ver=${1:-$v}

release=HEAD
rel=${2:-$release}

tj=taskjuggler-$ver
dir=`pwd`

echo "Building version" $tj tarball

rm -rf $tmpdir
mkdir $tmpdir
cd $tmpdir

cd $tmpdir
svn co http://einstein.suse.de/svn/taskjuggler -r $rel 1>/dev/null

mv taskjuggler/trunk $tj
# Remove subversion meta data
find $tj -name .cvsignore | xargs rm -f
find $tj -name .svn | xargs rm -rf

(cd $tj && make -f Makefile.cvs 1>/dev/null )

archive=$tj.tar.bz2

tar cjf $archive $tj

# Copy stuff home
cp $archive $dir
cd $dir

rm -rf $tmpdir

