#! /bin/sh

# Use a well defined LOCALE to create the reference files.
export LANG=en_US
export LC_COLLATE=POSIX 

export TASKJUGGLER=../../taskjuggler/taskjuggler
if test ! -x $TASKJUGGLER ; then
  export TASKJUGGLER=taskjuggler
else
  export TASKJUGGLER=../$TASKJUGGLER
fi

cd Scheduler/Correct
for f in *.tjp ; do
  referenceFile=`echo $f | sed s/\\\\\(.*\\\\\).tjp/\\\1-Reference.tjsp/g`
  exportFile=`echo $f | sed s/\\\\\(.*\\\\\).tjp/\\\1-Export.tjsp/g`
  $TASKJUGGLER $f
  if [ -f $exportFile ] ; then
    mv -f $exportFile $referenceFile
#    sed "1,4d" $exportFile > $referenceFile
    echo $referenceFile created
  fi
  rm -f *.html
done
cd ../..

cd HTML-Reports
for f in *.tjp ; do
  referenceFile=`echo $f | sed s/\\\\\(.*\\\\\).tjp/\\\1-Reference.html/g`
  ../../../taskjuggler/taskjuggler/taskjuggler $f | \
  fgrep -v TaskJuggler > $referenceFile || exit 1
  echo $referenceFile created
done

cd ..

