#! /bin/sh

export LANG=en_US
export LC_ALL=en_US
export LC_COLLATE=POSIX

errors=0
export TASKJUGGLER=../../taskjuggler/taskjuggler
if test ! -x $TASKJUGGLER ; then
  export TASKJUGGLER=taskjuggler
else
  export TASKJUGGLER=../$TASKJUGGLER
fi

function do_testing
{
  f=$1
  op=$2
  echo "Running test $f" >> ../log
  $TASKJUGGLER --debug 1 $TJARGS $f 2>> ../log
  if [ $? $op 0 ] ; then
    errors=$(( $errors + 1 ))
    echo "Test $f failed!" | tee -a ../log
  fi
  checkscript=`echo $f | sed s/\\\\\(.*\\\\\).tjp/\\\1.sh/g`
  referenceFile=`echo $f | sed s/\\\\\(.*\\\\\).tjp/\\\1-Reference.tjp/g`
  exportFile=`echo $f | sed s/\\\\\(.*\\\\\).tjp/\\\1-Export.tjp/g`
  if [ -x $checkscript ] ; then
    ./$checkscript 2>&1 >> ../log 
    if [ $? -ne 0 ] ; then
      errors=$(( $errors + 1 ))
      echo "Test $f failed (check script)!" | tee -a ../log
    fi
  fi
  if [ -f $referenceFile ] ; then
    cmp $exportFile $referenceFile 2>> ../log
    if [ $? -ne 0 ] ; then
      errors=$(( $errors + 1 ))
      echo "Test $f failed (Reference file differs)!" | tee -a ../log
      diff $referenceFile $exportFile | tee -a ../log
    else
      rm $exportFile
    fi
  fi
}

rm -f log
touch log

touch .timeStamp
sleep 1

TJARGS=""
if [ -f .tjargs ] ; then
  TJARGS=`cat .tjargs`
fi

cd Correct
echo "*** Running tests in Correct..." >> ../log
for f in *.tjp ; do
  do_testing $f -ne
done
cd ../Errors
echo "*** Running tests in Errors..." >> ../log
for f in *.tjp ; do
  do_testing $f -eq
done
cd ..

# remove all HTML files that are newer than the .timeStamp file
if [ $errors -eq 0 ] ; then
  find . -name "*.html" -newer .timeStamp | xargs /bin/rm -f
fi
/bin/rm -f .timeStamp
 
exit $errors

