#! /bin/sh

set errors=0
export TASKJUGGLER=../../taskjuggler/taskjuggler
if test ! -x $TASKJUGGLER ; then
  export TASKJUGGLER=taskjuggler
fi

function do_testing
{
  f=$1
  op=$2
  echo "Running test $f" >> log
  $TASKJUGGLER $f 2>> log
  if [ $? $op 0 ]; then
    errors=$(( $errors + 1 ))
    echo "Test $f failed!"
  fi
  checkscript=`echo $f | sed s/\\\\\(.*\\\\\).tjp/\\\1.sh/g`
  if [ -x $checkscript ] ; then
    sh $checkscript
    if [ $? -ne 0 ] ; then
      errors=$(( $errors + 1 ))
      echo "Text $f failed (check script)!"
    fi
  fi
}

rm -f log
touch log

for f in Correct/*.tjp ; do
  do_testing $f -ne
done
 
for f in Errors/*.tjp ; do
  do_testing $f -eq
done
 
exit $errors

