#! /bin/sh

set errors=0

dirs=`find * -maxdepth 0 -type d`

for d in $dirs ; do
  if [ $d != "CVS" ] ; then
    cd $d
    ./runtest
    errors=$(( $errors + $? ))
    if [ $? -ne 0 ] ; then
      echo "Test $d failed"
    fi
    cd ..
  fi
done

exit $errors

